version: 2

builds:
  - main: ./cmd/sidecar
    binary: sidecar
    ldflags:
      - -s -w -X main.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - README.md
      - CHANGELOG.md

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

# Note: Homebrew formula is manually maintained in marcus/homebrew-tap
# to build from source (avoids Gatekeeper warnings on macOS)
